### PR TITLE
Small string and colour changes

### PR DESCRIPTION
**Pull request by humdingerb**
just a suggestion... :)

### CODE REVIEW

**Comment by andimachovec** [comment]
Thanks humdinger for fixing the sentence casing stuff. The new colours are great too, easier on the eyes. I also like the colour difference between the peg selection view on the right and the main game board. 
One small problem that I've found: The image of the peg while being dragged shows a rectangle around the peg. You have to set the low color in line 160 of peg.cpp back to something transparent. (0 for the alpha channel). I'd suggest using all zeros to hint there isn't a real colour being used. I should have put a comment in the code probably ;-)

**Comment by humdingerb** [comment]
I was about to write the same, but didn't find the point to fix.
It's fixed now, thanks!

**Comment by humdingerb** [comment]
What do you think about making the active row a bit nicer, like:

screenshot2

**Comment by andimachovec** [comment]
Yeah, that looks great, I like it. On another note, I find the black result pegs a bit hard to distinguish from the empty holes. Do you have an idea how this could be improved? 

> I was about to write the same, but didn't find the point to fix.
I think I should separate the colour definitions (at least for the colors that can be changed)  from the actual code. That would make experimenting with different color schemes a lot easier and less error prone. I was first thinking about putting them in the rdef file but even better would in the config file.

**Comment by humdingerb** [comment]
Nobody says they have to be black, I suppose. :)
Actually, Some sort of help file would be nice. I'm not sure I remember Mastermind very well... For example, I had this game where I though 4 white pegs would mean I won. But I didn't...

peggy-win

Also, I kept playing a bit and I think a little stroke like this looks even nicer:

screenshot1

Maybe you should merge this PR and we'll leave further changes for another PR.

**Comment by andimachovec** [comment]
> Nobody says they have to be black, I suppose. :)

Well, it's a bit like a piano keyboard. The keys could be yellow and blue and you would still be able to play, but it would confuse the hell out of people. ;-) So I'd say we stick with black and white. 

> Actually, Some sort of help file would be nice. I'm not sure I remember Mastermind very well...
Black peg means right colour in the right position, white peg means right colour but in the wrong position. I'm not sure if I'm motivated to write a help file but we could put a link to wikipedia's mastermind page (I hope there is one) in the help menu. 

> Maybe you should merge this PR and we'll leave further changes for another PR.

Yeah, I'm going to do that. For next time it would probably be good to keep string changes and appearance changes in separate PRs.

**Comment by humdingerb** [comment]
You're right. I split my next proposed change into 2 PRs. :)

**Comment by andimachovec** [comment]
Great, thanks! :-)

**Pull request merged**
